In [151]:
import tensorflow as tf

from tensorflow.keras import datasets, layers, models


In [164]:
import pandas as pd
import numpy as np

df = pd.read_csv('dataset.csv')
df_f = df.copy()

In [193]:
count = 0
for i in df['tablero'].values:
    df_f['tablero'][count] = np.fromstring(i, dtype="float64", sep=' ').reshape((7, 7, 1))
    

    count+=1
    
for i in df_f['tablero'].values:
    print(i, "\n")
df_f

<ipython-input-193-b9c44340e17e>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_f['tablero'][count] = np.fromstring(i, dtype="float64", sep=' ').reshape((7, 7, 1))


[[[-1.]
  [-1.]
  [ 0.]
  [-1.]
  [-1.]
  [ 1.]
  [ 0.]]

 [[ 1.]
  [-1.]
  [-1.]
  [ 1.]
  [-1.]
  [-1.]
  [-1.]]

 [[ 1.]
  [-1.]
  [-1.]
  [ 0.]
  [-1.]
  [ 0.]
  [-1.]]

 [[ 1.]
  [-1.]
  [-1.]
  [-1.]
  [-1.]
  [-1.]
  [ 1.]]

 [[ 1.]
  [ 1.]
  [ 1.]
  [ 1.]
  [ 1.]
  [ 1.]
  [ 1.]]

 [[ 0.]
  [ 0.]
  [ 1.]
  [ 1.]
  [-1.]
  [ 0.]
  [ 1.]]

 [[ 0.]
  [ 0.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 1.]
  [ 0.]]] 

[[[ 1.]
  [-1.]
  [ 0.]
  [-1.]
  [ 0.]
  [-1.]
  [-1.]]

 [[ 1.]
  [-1.]
  [ 1.]
  [ 1.]
  [-1.]
  [ 0.]
  [-1.]]

 [[ 0.]
  [-1.]
  [ 1.]
  [ 1.]
  [-1.]
  [-1.]
  [ 0.]]

 [[ 1.]
  [-1.]
  [ 1.]
  [ 0.]
  [ 1.]
  [-1.]
  [-1.]]

 [[-1.]
  [-1.]
  [-1.]
  [ 1.]
  [ 1.]
  [-1.]
  [ 0.]]

 [[ 1.]
  [ 0.]
  [-1.]
  [ 1.]
  [ 1.]
  [ 1.]
  [-1.]]

 [[ 0.]
  [ 1.]
  [-1.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 0.]]] 

[[[ 1.]
  [ 0.]
  [ 1.]
  [ 1.]
  [-1.]
  [ 0.]
  [ 1.]]

 [[-1.]
  [ 1.]
  [ 1.]
  [ 1.]
  [-1.]
  [ 1.]
  [ 1.]]

 [[ 0.]
  [ 0.]
  [ 1.]
  [ 1.]
  [ 1.]
  [ 0.]
  [ 1.]]

 [[ 0.]
  

[[[-1.]
  [ 0.]
  [ 0.]
  [-1.]
  [ 0.]
  [-1.]
  [ 0.]]

 [[ 1.]
  [-1.]
  [-1.]
  [ 0.]
  [-1.]
  [ 0.]
  [-1.]]

 [[ 0.]
  [ 1.]
  [ 1.]
  [-1.]
  [ 0.]
  [-1.]
  [ 0.]]

 [[-1.]
  [ 1.]
  [-1.]
  [ 0.]
  [-1.]
  [ 0.]
  [-1.]]

 [[ 0.]
  [-1.]
  [ 0.]
  [ 0.]
  [ 0.]
  [-1.]
  [ 0.]]

 [[-1.]
  [ 0.]
  [-1.]
  [-1.]
  [-1.]
  [ 0.]
  [-1.]]

 [[ 0.]
  [-1.]
  [ 0.]
  [-1.]
  [ 0.]
  [-1.]
  [ 0.]]] 

[[[ 1.]
  [ 1.]
  [-1.]
  [-1.]
  [ 0.]
  [-1.]
  [ 0.]]

 [[ 1.]
  [ 0.]
  [ 1.]
  [-1.]
  [-1.]
  [-1.]
  [-1.]]

 [[ 0.]
  [ 1.]
  [-1.]
  [-1.]
  [ 0.]
  [-1.]
  [-1.]]

 [[ 1.]
  [ 0.]
  [ 1.]
  [ 1.]
  [-1.]
  [ 0.]
  [-1.]]

 [[ 0.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 1.]
  [-1.]
  [ 0.]]

 [[ 1.]
  [ 0.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 1.]
  [-1.]]

 [[ 0.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 0.]
  [-1.]
  [ 0.]]] 

[[[-1.]
  [-1.]
  [ 0.]
  [ 0.]
  [-1.]
  [-1.]
  [ 0.]]

 [[-1.]
  [-1.]
  [-1.]
  [-1.]
  [ 0.]
  [-1.]
  [-1.]]

 [[ 0.]
  [-1.]
  [-1.]
  [-1.]
  [-1.]
  [ 0.]
  [-1.]]

 [[-1.]
  

[[[ 0.]
  [-1.]
  [ 0.]
  [-1.]
  [-1.]
  [-1.]
  [-1.]]

 [[-1.]
  [-1.]
  [-1.]
  [ 0.]
  [-1.]
  [ 0.]
  [-1.]]

 [[ 0.]
  [-1.]
  [ 0.]
  [-1.]
  [ 0.]
  [-1.]
  [-1.]]

 [[-1.]
  [ 0.]
  [-1.]
  [-1.]
  [ 0.]
  [-1.]
  [ 0.]]

 [[ 0.]
  [-1.]
  [ 0.]
  [-1.]
  [ 0.]
  [ 0.]
  [ 0.]]

 [[-1.]
  [ 0.]
  [-1.]
  [-1.]
  [-1.]
  [-1.]
  [-1.]]

 [[ 0.]
  [-1.]
  [-1.]
  [ 0.]
  [-1.]
  [ 1.]
  [ 0.]]] 

[[[ 0.]
  [-1.]
  [ 0.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 0.]]

 [[-1.]
  [ 0.]
  [-1.]
  [ 1.]
  [ 1.]
  [ 0.]
  [ 1.]]

 [[-1.]
  [-1.]
  [-1.]
  [ 0.]
  [ 1.]
  [ 1.]
  [ 0.]]

 [[ 0.]
  [-1.]
  [ 0.]
  [-1.]
  [ 0.]
  [ 1.]
  [ 1.]]

 [[-1.]
  [-1.]
  [-1.]
  [-1.]
  [ 1.]
  [ 1.]
  [ 0.]]

 [[ 1.]
  [ 1.]
  [ 1.]
  [-1.]
  [-1.]
  [ 1.]
  [ 1.]]

 [[ 0.]
  [ 1.]
  [ 1.]
  [-1.]
  [-1.]
  [ 1.]
  [ 0.]]] 

[[[ 1.]
  [ 0.]
  [ 0.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 0.]]

 [[ 0.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 1.]]

 [[ 1.]
  [ 1.]
  [ 1.]
  [ 0.]
  [-1.]
  [ 1.]
  [ 1.]]

 [[ 1.]
  

  [ 0.]]] 

[[[ 0.]
  [-1.]
  [-1.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 0.]]

 [[-1.]
  [ 1.]
  [ 1.]
  [ 1.]
  [ 1.]
  [ 0.]
  [ 1.]]

 [[-1.]
  [ 1.]
  [ 1.]
  [-1.]
  [ 1.]
  [ 1.]
  [ 1.]]

 [[-1.]
  [ 1.]
  [-1.]
  [ 0.]
  [-1.]
  [ 1.]
  [-1.]]

 [[ 0.]
  [-1.]
  [ 0.]
  [-1.]
  [ 0.]
  [-1.]
  [-1.]]

 [[-1.]
  [-1.]
  [-1.]
  [ 0.]
  [-1.]
  [-1.]
  [ 1.]]

 [[ 0.]
  [-1.]
  [ 0.]
  [-1.]
  [-1.]
  [ 1.]
  [ 0.]]] 

[[[ 0.]
  [ 1.]
  [ 1.]
  [-1.]
  [ 0.]
  [-1.]
  [ 0.]]

 [[ 1.]
  [ 1.]
  [-1.]
  [ 0.]
  [-1.]
  [ 0.]
  [-1.]]

 [[ 0.]
  [ 1.]
  [-1.]
  [-1.]
  [ 0.]
  [-1.]
  [-1.]]

 [[ 1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [-1.]
  [ 0.]]

 [[ 1.]
  [ 0.]
  [ 1.]
  [ 1.]
  [ 1.]
  [-1.]
  [-1.]]

 [[ 0.]
  [ 1.]
  [ 1.]
  [ 0.]
  [-1.]
  [-1.]
  [-1.]]

 [[ 1.]
  [ 0.]
  [ 1.]
  [ 0.]
  [-1.]
  [ 1.]
  [ 0.]]] 

[[[ 0.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 0.]]

 [[-1.]
  [-1.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 0.]
  [ 1.]]

 [[-1.]
  [-1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [ 0.]]

  [ 0.]]] 

[[[-1.]
  [ 0.]
  [-1.]
  [ 0.]
  [-1.]
  [-1.]
  [ 0.]]

 [[ 1.]
  [-1.]
  [-1.]
  [-1.]
  [-1.]
  [ 0.]
  [-1.]]

 [[ 1.]
  [ 1.]
  [ 1.]
  [ 0.]
  [-1.]
  [-1.]
  [ 0.]]

 [[-1.]
  [ 1.]
  [ 1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]]

 [[-1.]
  [-1.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 1.]
  [-1.]]

 [[ 1.]
  [ 0.]
  [ 0.]
  [ 1.]
  [ 0.]
  [ 1.]
  [-1.]]

 [[-1.]
  [-1.]
  [-1.]
  [ 1.]
  [ 1.]
  [-1.]
  [ 0.]]] 

[[[ 1.]
  [-1.]
  [ 0.]
  [-1.]
  [-1.]
  [ 0.]
  [-1.]]

 [[ 1.]
  [-1.]
  [-1.]
  [ 0.]
  [-1.]
  [-1.]
  [ 0.]]

 [[ 1.]
  [ 0.]
  [-1.]
  [-1.]
  [ 0.]
  [-1.]
  [-1.]]

 [[ 1.]
  [ 0.]
  [-1.]
  [-1.]
  [-1.]
  [-1.]
  [ 1.]]

 [[ 1.]
  [ 1.]
  [-1.]
  [ 1.]
  [ 0.]
  [-1.]
  [ 0.]]

 [[ 0.]
  [ 1.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 1.]
  [ 1.]]

 [[ 1.]
  [ 0.]
  [ 1.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 0.]]] 

[[[-1.]
  [-1.]
  [ 0.]
  [ 0.]
  [-1.]
  [-1.]
  [-1.]]

 [[ 0.]
  [-1.]
  [ 0.]
  [-1.]
  [ 0.]
  [-1.]
  [ 0.]]

 [[-1.]
  [-1.]
  [ 0.]
  [-1.]
  [-1.]
  [ 0.]
  [-1.]]

  [ 0.]]] 

[[[ 0.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 1.]
  [-1.]
  [-1.]]

 [[ 1.]
  [ 0.]
  [ 1.]
  [ 0.]
  [ 1.]
  [-1.]
  [ 0.]]

 [[ 0.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 1.]
  [-1.]
  [-1.]]

 [[ 1.]
  [ 0.]
  [ 1.]
  [-1.]
  [-1.]
  [ 0.]
  [ 1.]]

 [[ 0.]
  [ 1.]
  [-1.]
  [ 0.]
  [-1.]
  [ 1.]
  [ 1.]]

 [[ 1.]
  [ 1.]
  [ 0.]
  [-1.]
  [ 0.]
  [-1.]
  [-1.]]

 [[ 1.]
  [ 1.]
  [-1.]
  [-1.]
  [-1.]
  [ 1.]
  [ 0.]]] 

[[[ 0.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 0.]]

 [[ 1.]
  [ 0.]
  [ 1.]
  [ 0.]
  [ 1.]
  [-1.]
  [-1.]]

 [[-1.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 1.]
  [-1.]
  [ 0.]]

 [[ 0.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [-1.]
  [-1.]]

 [[-1.]
  [-1.]
  [ 1.]
  [-1.]
  [-1.]
  [ 0.]
  [-1.]]

 [[ 0.]
  [-1.]
  [ 0.]
  [ 1.]
  [-1.]
  [-1.]
  [ 1.]]

 [[-1.]
  [ 0.]
  [-1.]
  [-1.]
  [ 0.]
  [-1.]
  [ 0.]]] 

[[[ 0.]
  [-1.]
  [-1.]
  [-1.]
  [-1.]
  [ 0.]
  [ 0.]]

 [[-1.]
  [ 0.]
  [ 0.]
  [-1.]
  [-1.]
  [-1.]
  [ 0.]]

 [[ 0.]
  [-1.]
  [-1.]
  [ 0.]
  [-1.]
  [ 0.]
  [-1.]]

[[[ 0.]
  [ 1.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 1.]
  [ 0.]]

 [[ 1.]
  [ 0.]
  [ 1.]
  [ 1.]
  [ 0.]
  [ 0.]
  [ 1.]]

 [[ 0.]
  [ 1.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 1.]
  [ 1.]]

 [[ 1.]
  [ 0.]
  [ 1.]
  [ 1.]
  [ 1.]
  [ 0.]
  [ 0.]]

 [[ 1.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 1.]
  [ 1.]
  [ 1.]]

 [[ 0.]
  [ 1.]
  [ 1.]
  [ 0.]
  [ 1.]
  [-1.]
  [-1.]]

 [[ 1.]
  [ 0.]
  [ 1.]
  [ 0.]
  [ 1.]
  [-1.]
  [ 0.]]] 

[[[ 0.]
  [-1.]
  [-1.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 0.]]

 [[-1.]
  [ 0.]
  [-1.]
  [ 1.]
  [ 1.]
  [ 0.]
  [ 1.]]

 [[ 0.]
  [-1.]
  [ 1.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 0.]]

 [[-1.]
  [ 1.]
  [ 1.]
  [-1.]
  [ 1.]
  [ 0.]
  [ 1.]]

 [[-1.]
  [ 0.]
  [-1.]
  [-1.]
  [-1.]
  [ 1.]
  [ 0.]]

 [[-1.]
  [-1.]
  [-1.]
  [ 1.]
  [-1.]
  [ 1.]
  [ 1.]]

 [[ 0.]
  [-1.]
  [-1.]
  [ 1.]
  [ 1.]
  [ 1.]
  [ 0.]]] 

[[[ 1.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 0.]]

 [[ 0.]
  [ 1.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 0.]
  [ 1.]]

 [[ 1.]
  [ 1.]
  [-1.]
  [ 1.]
  [ 0.]
  [ 1.]
  [ 0.]]

 [[ 1.]
  

resultado                                            tablero
0             1  [[[-1.0], [-1.0], [0.0], [-1.0], [-1.0], [1.0]...
1             0  [[[1.0], [-1.0], [0.0], [-1.0], [0.0], [-1.0],...
2             1  [[[1.0], [0.0], [1.0], [1.0], [-1.0], [0.0], [...
3             0  [[[0.0], [-1.0], [0.0], [-1.0], [-1.0], [1.0],...
4             0  [[[1.0], [1.0], [-1.0], [-1.0], [-1.0], [0.0],...
...         ...                                                ...
1005          1  [[[1.0], [0.0], [1.0], [0.0], [1.0], [1.0], [0...
1006          1  [[[-1.0], [0.0], [-1.0], [0.0], [-1.0], [0.0],...
1007          0  [[[1.0], [0.0], [1.0], [0.0], [1.0], [-1.0], [...
1008          0  [[[-1.0], [0.0], [-1.0], [0.0], [-1.0], [-1.0]...
1009          1  [[[0.0], [1.0], [1.0], [-1.0], [0.0], [1.0], [...

[1010 rows x 2 columns]

In [194]:
model = models.Sequential()
model.add(layers.Conv2D(7, (4, 4), activation='relu', input_shape=(7, 7, 1))) #data_format='channels_first'
model.add(layers.MaxPooling2D(2,2))
model.add(layers.Flatten())
model.add(layers.Dense(49, activation='relu'))
model.add(layers.Dense(3, activation='softmax'))
model.compile(optimizer='adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), metrics=['accuracy'])

In [195]:
df_f
model.summary()


Model: "sequential_65"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_45 (Conv2D)           (None, 4, 4, 7)           119       
_________________________________________________________________
max_pooling2d_26 (MaxPooling (None, 2, 2, 7)           0         
_________________________________________________________________
flatten_10 (Flatten)         (None, 28)                0         
_________________________________________________________________
dense_48 (Dense)             (None, 49)                1421      
_________________________________________________________________
dense_49 (Dense)             (None, 3)                 150       
Total params: 1,690
Trainable params: 1,690
Non-trainable params: 0
_________________________________________________________________


In [196]:
#print(df_f["resultado"][39])

#df_f["tablero"] = df["tablero"]

#print(df_f)

In [197]:
#df_f.to_csv('dataset.csv', header=True, index=False)

In [198]:
#print(type(df_f['tablero'].values))

#print(pd.array(df_f['tablero'].values, dtype='Int32'))

#print((df_f['tablero'].tolist()))

#table_train =  np.asarray(df_f['tablero'].to_numpy().tolist())

#df_f['resultado'].replace({-1:2}, inplace=True)

#print(res)

table_train = tf.convert_to_tensor(df_f['tablero'].tolist())
res_train = tf.convert_to_tensor(df_f['resultado'].tolist())

train_data = tf.data.Dataset.from_tensor_slices((table_train, res_train))
#valid_data = tf.data.Dataset.from_tensor_slices((testMixed, testVocals))

print(res_train)


#table_train = np.asarray(df_f['tablero'].values).astype(np.float32)
#res_train = np.asarray(df_f["resultado"].values).astype(np.float32)
history = model.fit(table_train, res_train, epochs = 100) #validation_data=(test_images, test_labels)

tf.Tensor([1 0 1 ... 0 0 1], shape=(1010,), dtype=int32)
Epoch 1/100
32/32 [==============================] - 1s 2ms/step - loss: 0.9450 - accuracy: 0.5695
Epoch 2/100
32/32 [==============================] - 0s 3ms/step - loss: 0.6306 - accuracy: 0.7853
Epoch 3/100
32/32 [==============================] - 0s 2ms/step - loss: 0.4713 - accuracy: 0.8271
Epoch 4/100
32/32 [==============================] - 0s 2ms/step - loss: 0.4466 - accuracy: 0.8214
Epoch 5/100
32/32 [==============================] - 0s 2ms/step - loss: 0.3828 - accuracy: 0.8557
Epoch 6/100
32/32 [==============================] - 0s 2ms/step - loss: 0.3569 - accuracy: 0.8619
Epoch 7/100
32/32 [==============================] - 0s 2ms/step - loss: 0.3102 - accuracy: 0.8918
Epoch 8/100
32/32 [==============================] - 0s 2ms/step - loss: 0.3243 - accuracy: 0.8888
Epoch 9/100
32/32 [==============================] - 0s 2ms/step - loss: 0.2692 - accuracy: 0.9053
Epoch 10/100
32/32 [==============================] 

32/32 [==============================] - 0s 2ms/step - loss: 0.0808 - accuracy: 0.9711
Epoch 83/100
32/32 [==============================] - 0s 2ms/step - loss: 0.0702 - accuracy: 0.9748
Epoch 84/100
32/32 [==============================] - 0s 2ms/step - loss: 0.0643 - accuracy: 0.9836
Epoch 85/100
32/32 [==============================] - 0s 2ms/step - loss: 0.0588 - accuracy: 0.9812
Epoch 86/100
32/32 [==============================] - 0s 2ms/step - loss: 0.0618 - accuracy: 0.9776
Epoch 87/100
32/32 [==============================] - 0s 2ms/step - loss: 0.0771 - accuracy: 0.9757
Epoch 88/100
32/32 [==============================] - 0s 2ms/step - loss: 0.0722 - accuracy: 0.9746
Epoch 89/100
32/32 [==============================] - 0s 2ms/step - loss: 0.0570 - accuracy: 0.9809
Epoch 90/100
32/32 [==============================] - 0s 2ms/step - loss: 0.0565 - accuracy: 0.9830
Epoch 91/100
32/32 [==============================] - 0s 2ms/step - loss: 0.0594 - accuracy: 0.9816
Epoch 92/100


In [191]:
model.summary()


Model: "sequential_64"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_44 (Conv2D)           (None, 4, 4, 7)           119       
_________________________________________________________________
max_pooling2d_25 (MaxPooling (None, 2, 2, 7)           0         
_________________________________________________________________
flatten_9 (Flatten)          (None, 28)                0         
_________________________________________________________________
dense_46 (Dense)             (None, 49)                1421      
_________________________________________________________________
dense_47 (Dense)             (None, 3)                 150       
Total params: 1,690
Trainable params: 1,690
Non-trainable params: 0
_________________________________________________________________


In [199]:
#print(np.array(df_f['tablero'].tolist()[0], dtype="float64"))

predict = model.predict(tf.convert_to_tensor(df_f['tablero'].tolist()))#.to_numpy()[0].reshape((-1, 49)))

In [200]:
predict

array([[1.7668901e-04, 9.5792812e-01, 4.1895263e-02],
       [9.9852610e-01, 6.3800217e-06, 1.4673889e-03],
       [7.3921723e-11, 1.0000000e+00, 2.1250582e-08],
       ...,
       [9.9999952e-01, 1.4561418e-09, 4.5573987e-07],
       [9.9999988e-01, 2.9244355e-14, 6.1000783e-08],
       [4.8424791e-08, 9.9993145e-01, 6.8547604e-05]], dtype=float32)